"""Ajout code_id et table TimesheetModifier

Revision ID: 70a9a1151782
Revises: 5f15d9fc3b84
Create Date: 2025-07-07 19:52:07.984885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a9a1151782'
down_revision = '5f15d9fc3b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timesheet_modifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timesheet_id', sa.Integer(), nullable=True),
    sa.Column('modifier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modifier_id'], ['modifier.id'], ),
    sa.ForeignKeyConstraint(['timesheet_id'], ['timesheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modifier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valeur_minutes', sa.Integer(), nullable=True))

    with op.batch_alter_table('timesheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'code', ['code_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('code_id')

    with op.batch_alter_table('modifier', schema=None) as batch_op:
        batch_op.drop_column('valeur_minutes')

    op.drop_table('timesheet_modifier')
    # ### end Alembic commands ###
