"""Ajout employee_type à User

Revision ID: 7f13d6e83b40
Revises: e5772af38118
Create Date: 2025-07-07 18:16:07.685096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f13d6e83b40'
down_revision = 'e5772af38118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('employee_type')

    # ### end Alembic commands ###
